spring:
  jackson:
    time-zone: UTC
    date-format: "yyyy-MM-dd HH:mm:ss"

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/core_user_service
    username: postgres
    password: root

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true

  sql:
    init:
      mode: always

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 50
        failure-rate-threshold: 50
    instances:
      user-service:
        sliding-window-size: 30
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 7
        automatic-transition-from-open-to-half-open-enabled: true

logging:
  level:
    root: INFO
    ru.practicum: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.jdbc.datasource.init: DEBUG