server:
  port: 0

spring:
  jackson:
    time-zone: UTC
    date-format: "yyyy-MM-dd HH:mm:ss"

  cloud:
    config:
      fail-fast: true
      retry:
        initial-interval: 3000
        max-attempts: 10
        max-interval: 10000

feign:
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 50
        failure-rate-threshold: 50
    instances:
      user-service:
        sliding-window-size: 30
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 7
        automatic-transition-from-open-to-half-open-enabled: true
      main-service:
        sliding-window-size: 30
        wait-duration-in-open-state: 10000
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: COUNT_BASED
        minimum-number-of-calls: 7
        automatic-transition-from-open-to-half-open-enabled: true

logging:
  level:
    root: INFO
    ru.practicum: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.transaction.interceptor: DEBUG
    org.springframework.orm.jpa.JpaTransactionManager: INFO