jackson:
  time-zone: UTC

logging:
  level:
    root: INFO
    ru.practicum.server: TRACE
    org.springframework.orm.jpa: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.transaction.interceptor: DEBUG
    org.springframework.orm.jpa.JpaTransactionManager: INFO